### ISSUE TITLE
Cookbook-provided package provider still used on Chef 12

### ISSUE THREAD

**Issue by amarshall** [chef-cookbooks/homebrew#115]
### Cookbook version
2.1.2

### Chef-client version
12.17.44

### Platform Details
macOS 10.12.2 (x86_64-darwin13)

### Scenario:
Marking a package with `action :upgrade` fails when the package is not installed, which, per #58 is intentionally left broken on Chef <12, but should work on Chef 12.

### Steps to Reproduce:
Mark a package that has never been installed with `action :upgrade`. Why precisely the cookbook-provided package provider is used on Chef 12 is unknown. Note that, while the “git” package is used here, substituting an alternative package yields the same failure.

### Expected Result:
Successfully installs package, seemingly using the built-in (non-cookbook) package provider.

### Actual Result:
```
-----> Starting Kitchen (v1.14.2)
-----> Converging <>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.3.0...
       Removing non-cookbook files before transfer
       Preparing roles
       Preparing solo.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <>
       Starting Chef Client, version 12.17.44
       resolving cookbooks for run list: ["homebrew", "workstation::git"]
       Synchronizing Cookbooks:
         - homebrew (2.1.2)
         - build-essential (7.0.2)
         - workstation (0.0.0)
         - mingw (1.2.4)
         - seven_zip (2.0.2)
         - compat_resource (12.16.2)
         - windows (2.1.1)
         - ohai (4.2.3)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 5 resources
       Recipe: homebrew::default
         * remote_file[/tmp/kitchen/cache/homebrew_go] action create (up to date)
         * execute[install homebrew] action run (skipped due to not_if)
         * homebrew_package[git] action install (skipped due to not_if)
         * execute[update homebrew from github] action run
           - execute /usr/local/bin/brew update || true
       Recipe: workstation::git
         * homebrew_package[git] action upgrade

           ================================================================================
           Error executing action `upgrade` on resource 'homebrew_package[git]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of brew upgrade git ----
           STDOUT:
           STDERR: Error: git not installed
           ---- End output of brew upgrade git ----
           Ran brew upgrade git returned 1

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/homebrew/libraries/homebrew_package.rb:95:in `get_response_from_command'
           /tmp/kitchen/cache/cookbooks/homebrew/libraries/homebrew_package.rb:70:in `brew'
           /tmp/kitchen/cache/cookbooks/homebrew/libraries/homebrew_package.rb:54:in `upgrade_package'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/workstation/recipes/git.rb

             1: package 'git' do
             2:   action :upgrade
             3: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/workstation/recipes/git.rb:1:in `from_file'

           homebrew_package("git") do
             package_name "git"
             action [:upgrade]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :package
             cookbook_name "workstation"
             recipe_name "git"
           end

           Platform:
           ---------
           x86_64-darwin13


       Running handlers:
       [2016-12-19T08:23:35-08:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-12-19T08:23:35-08:00] ERROR: Exception handlers complete
       Chef Client failed. 1 resources updated in 15 seconds
       [2016-12-19T08:23:35-08:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-12-19T08:23:35-08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-12-19T08:23:35-08:00] ERROR: homebrew_package[git] (workstation::git line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of brew upgrade git ----
       STDOUT:
       STDERR: Error: git not installed
       ---- End output of brew upgrade git ----
       Ran brew upgrade git returned 1
       [2016-12-19T08:23:35-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by tas50** [comment]
I need to finish up #107 and ship it to resolve this

**Comment by tas50** [comment]
It's been removed in master
