### ISSUE TITLE
Package resources crash Chef 13.2

### ISSUE THREAD

**Issue by adambrenecki** [chef-cookbooks/homebrew#127]
### Cookbook version
`4.2.0`

### Chef-client version
```
$ chef --version
Chef Development Kit Version: 2.0.28
chef-client version: 13.2.20
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 6.2.0
kitchen version: 1.16.0
inspec version: 1.31.1
```

### Platform Details
macOS Sierra 10.12.6

### Scenario:
I'm trying to install a Homebrew package, but the `package` resource causes Chef to crash.

### Steps to Reproduce:
Create a recipe consisting of:
```
package 'p7zip'
```
Run it using the command:
```
chef-client --local-mode --runlist 'homecooked::test'
```

### Expected Result:
The `p7zip` package is installed.

### Actual Result:
```
================================================================================
Recipe Compile Error in /Users/adam/.chef/local-mode-cache/cache/cookbooks/homebrew/libraries/homebrew_package.rb
================================================================================

NoMethodError
-------------
undefined method `find' for Chef::Platform:Class

Cookbook Trace:
---------------
  /Users/adam/.chef/local-mode-cache/cache/cookbooks/homebrew/libraries/homebrew_package.rb:26:in `<top (required)>'

Relevant File Content:
----------------------
/Users/adam/.chef/local-mode-cache/cache/cookbooks/homebrew/libraries/homebrew_package.rb:

 19:  # limitations under the License.
 20:  #
 21:  # cookbook libraries are unconditionally included if the cookbook is
 22:  # present on a node. This approach should avoid creating this class if
 23:  # the node already has Chef::Provider::Package::Homebrew, such as with
 24:  # Chef 12.
 25:  # https://github.com/chef/chef-rfc/blob/master/rfc016-homebrew-osx-package-provider.md
 26>> unless defined?(Chef::Provider::Package::Homebrew) && Chef::Platform.find('mac_os_x', nil)[:package] == Chef::Provider::Package::Homebrew
 27:    require 'chef/provider/package'
 28:    require 'chef/resource/package'
 29:    require 'chef/platform'
 30:    require 'chef/mixin/shell_out'
 31:  
 32:    class Chef
 33:      class Provider
 34:        class Package
 35:          # Package

System Info:
------------
chef_version=13.2.20
platform=mac_os_x
platform_version=10.12.6
ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin14]
program_name=chef-client worker: ppid=3963;start=08:29:46;
executable=/opt/chefdk/bin/chef-client


Running handlers:
[2017-07-29T08:30:02+09:30] ERROR: Running exception handlers
[2017-07-29T08:30:02+09:30] ERROR: Running exception handlers
Running handlers complete
[2017-07-29T08:30:02+09:30] ERROR: Exception handlers complete
[2017-07-29T08:30:02+09:30] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 15 seconds
[2017-07-29T08:30:02+09:30] FATAL: Stacktrace dumped to /Users/adam/.chef/local-mode-cache/cache/chef-stacktrace.out
[2017-07-29T08:30:02+09:30] FATAL: Stacktrace dumped to /Users/adam/.chef/local-mode-cache/cache/chef-stacktrace.out
[2017-07-29T08:30:02+09:30] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-07-29T08:30:02+09:30] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-07-29T08:30:02+09:30] ERROR: undefined method `find' for Chef::Platform:Class
[2017-07-29T08:30:02+09:30] ERROR: undefined method `find' for Chef::Platform:Class
[2017-07-29T08:30:02+09:30] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[2017-07-29T08:30:02+09:30] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

```
#### /Users/adam/.chef/local-mode-cache/cache/chef-stacktrace.out
```
Generated at 2017-07-29 08:30:02 +0930
NoMethodError: undefined method `find' for Chef::Platform:Class
/Users/adam/.chef/local-mode-cache/cache/cookbooks/homebrew/libraries/homebrew_package.rb:26:in `<top (required)>'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/run_context/cookbook_compiler.rb:224:in `load'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/run_context/cookbook_compiler.rb:224:in `block in load_libraries_from_cookbook'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/run_context/cookbook_compiler.rb:220:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/run_context/cookbook_compiler.rb:220:in `load_libraries_from_cookbook'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/run_context/cookbook_compiler.rb:101:in `block in compile_libraries'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/run_context/cookbook_compiler.rb:100:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/run_context/cookbook_compiler.rb:100:in `compile_libraries'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/run_context/cookbook_compiler.rb:72:in `compile'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/run_context.rb:192:in `load'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:513:in `setup_run_context'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:281:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:279:in `fork'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:232:in `run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:457:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:457:in `interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:441:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:59:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/bin/chef-client:26:in `<top (required)>'
/usr/local/bin/chef-client:263:in `load'
/usr/local/bin/chef-client:263:in `<main>'
```

**Comment by iennae** [comment]
Can you please check that you are using the latest version of the cookbook? The library you are using is from an older version of the cookbook.

**Comment by nerocrux** [comment]
Same problem here. Using ```4.2.0``` and chef-client ```13.3.42```.

**Comment by adambrenecki** [comment]
Ooh, sorry, I forgot to update this ticket. In my case it turns out that I wasn't calling `berks vendor` in a script when I thought I was, or something along those lines.

**Comment by nerocrux** [comment]
Figured out that one of my cookbook's dependencies uses nodejs cookbook v3.0.0 which causes this problem.
This error disappears after nodejs cookbook being updated to v4.0.0.

**Comment by adambrenecki** [comment]
Since neither of us have actually found a bug in the Homebrew cookbook itself, I'll close this.
