### ISSUE TITLE
Cask resource seems to fail to compile on some non-darwin machine

### ISSUE THREAD

**Issue by Annih** [chef-cookbooks/homebrew#131]
### Cookbook version
5.0.1

### Chef-client version
13.8.5 (ruby 2.4.0)

### Platform Details
CentOS Linux release 7.3.1611 (Core)

### Scenario:
When trying to run a basic ChefSpec test for CentOS of a cookbook that does only include homebrew has a dependency.

### Steps to Reproduce:
Create a ChefSpec test as below:
```ruby
require 'spec_helper'
describe 'nexus3::default' 
  context 'When all attributes are default, on centos 7.2.1511' do
    let(:chef_run) do
      ::ChefSpec::SoloRunner.new(platform: 'centos', version:  '7.2.1511').converge(described_recipe)
    end
    it 'converges successfully' do
      expect { chef_run }.to_not raise_error
    end
  end
end
```

### Expected Result:
No error.

### Actual Result:
```expected no Exception, got #<Chef::Exceptions::ValidationFailed: Property owner must be one of: String!  You passed nil.> with backtrace:
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/mixin/params_validate.rb:431:in `_pv_is'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/mixin/params_validate.rb:107:in `block (2 levels) in validate'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/mixin/params_validate.rb:104:in `each'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/mixin/params_validate.rb:104:in `block in validate'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/mixin/params_validate.rb:94:in `each'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/mixin/params_validate.rb:94:in `validate'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/property.rb:473:in `validate'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/property.rb:677:in `coerce_and_validate'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/property.rb:658:in `input_to_stored_value'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/property.rb:131:in `initialize'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/property.rb:51:in `new'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/property.rb:51:in `derive'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/mixin/properties.rb:147:in `property_type'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/mixin/properties.rb:127:in `property'
  # /tmp/chefspec20180309-7124-zbtmhnfile_cache_path/cookbooks/homebrew/resources/cask.rb:25:in `class_from_file'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/mixin/from_file.rb:42:in `class_eval'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/mixin/from_file.rb:42:in `class_from_file'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/resource/lwrp_base.rb:58:in `build_from_file'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/run_context/cookbook_compiler.rb:253:in `load_lwrp_resource'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/run_context/cookbook_compiler.rb:238:in `block in load_lwrps_from_cookbook'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/run_context/cookbook_compiler.rb:237:in `each'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/run_context/cookbook_compiler.rb:237:in `load_lwrps_from_cookbook'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/run_context/cookbook_compiler.rb:143:in `block in compile_lwrps'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/run_context/cookbook_compiler.rb:142:in `each'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/run_context/cookbook_compiler.rb:142:in `compile_lwrps'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/run_context.rb:191:in `load'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chef-13.8.5/lib/chef/client.rb:513:in `setup_run_context'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chefspec-7.1.2/lib/chefspec/solo_runner.rb:119:in `converge'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chefspec-7.1.2/lib/chefspec/server_runner.rb:44:in `converge'
  # ./spec/unit/recipes/default_spec.rb:30:in `block (3 levels) in <top (required)>'
  # ./spec/unit/recipes/default_spec.rb:34:in `block (4 levels) in <top (required)>'
  # /home/jenkins/.gem/ruby/2.4.0/gems/chefspec-7.1.2/lib/chefspec/expect_exception.rb:15:in `matches?'
  # ./spec/unit/recipes/default_spec.rb:34:in `block (3 levels) in <top (required)>'
```

@tas50  I'm really sorry to contact you again just after a release, but I think this might be related to https://github.com/chef-cookbooks/homebrew/commit/39c0188f1ee734766d74657a556c3c2f959a819b#diff-787cb5c90e5144bfc53079ddc72d80c2R25. Personnally I don't use `homebrew`, but just having it as a dependency break the tests.

Please also note that on my workstation (not my Jenkins machine) with the same gems and cookbooks it works fine :D (archlinux over WSL - ruby 2.5.0)

**Comment by Annih** [comment]
One easy fix could be to wrap the default value in a lazy evaluator, I don't have time to dig more right now, sorry.

**Comment by Annih** [comment]
Ok it seems better with the latest version `5.0.3`
