### ISSUE TITLE
Homebrew Environmental Var

### ISSUE THREAD

**Issue by bdwyertech** [chef-cookbooks/homebrew#87]
Looks like this commit got merged in and is now causing issues with the `homebrew_package` library.

The brew bash script now populates environmental variables which the config library is dependent upon.

https://github.com/Homebrew/homebrew/commit/390e327f55126f7ee9519bc6c03a0c0aa14f7168

```
Recipe: homebrew::install_formulas
  * homebrew_package[homebrew/php/composer] action install

    ================================================================================
    Error executing action `install` on resource 'homebrew_package[homebrew/php/composer]'
    ================================================================================

    TypeError
    ---------
    no implicit conversion of nil into String

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/homebrew/libraries/homebrew_package.rb:94:in `version_from_formula'
    /var/chef/cache/cookbooks/homebrew/libraries/homebrew_package.rb:74:in `current_installed_version'
    /var/chef/cache/cookbooks/homebrew/libraries/homebrew_package.rb:44:in `load_current_resource'
```

Something like the following needs to be added to the `homebrew_package` library

```
  ENV['HOMEBREW_PREFIX'] = brew_cmd.stdout.chomp
  ENV['HOMEBREW_REPOSITORY'] = ENV['HOMEBREW_PREFIX']
  ENV['HOMEBREW_LIBRARY'] = ::File.join(ENV['HOMEBREW_REPOSITORY'], 'Library')
  ENV['HOMEBREW_CELLAR'] = ::File.join(ENV['HOMEBREW_PREFIX'], 'Cellar')
```

**Comment by keen99** [comment]
thanks for tracking this down - this broke my world this morning as well.
